"""add shared links tables

Revision ID: b57236d395af
Revises: 4634ce7e177d
Create Date: 2026-06-21 11:04:50.466299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57236d395af'
down_revision: Union[str, Sequence[str], None] = '4634ce7e177d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('include_attachments', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot_data', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_links_id'), 'shared_links', ['id'], unique=False)
    op.create_index(op.f('ix_shared_links_token'), 'shared_links', ['token'], unique=True)
    op.create_table('shared_link_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_link_id', sa.String(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shared_link_id'], ['shared_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_link_audit_logs_id'), 'shared_link_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_link_audit_logs_id'), table_name='shared_link_audit_logs')
    op.drop_table('shared_link_audit_logs')
    op.drop_index(op.f('ix_shared_links_token'), table_name='shared_links')
    op.drop_index(op.f('ix_shared_links_id'), table_name='shared_links')
    op.drop_table('shared_links')
    # ### end Alembic commands ###
