CREATE TABLE `recomp_records` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`date` integer NOT NULL,
	`weight` real NOT NULL,
	`bmi` real NOT NULL,
	`body_fat_pct` real NOT NULL,
	`subcutaneous_fat_pct` real NOT NULL,
	`heart_rate` real,
	`heart_index` real,
	`visceral_fat` real NOT NULL,
	`body_water_pct` real NOT NULL,
	`skeletal_muscle_mass_pct` real NOT NULL,
	`muscle_mass` real NOT NULL,
	`bone_mass` real NOT NULL,
	`protein_pct` real NOT NULL,
	`bmr` real NOT NULL,
	`metabolic_age` real NOT NULL,
	`fat_mass` real NOT NULL,
	`moisture_content` real NOT NULL,
	`skeletal_muscle_mass` real NOT NULL,
	`muscle_rate_pct` real NOT NULL,
	`protein_mass` real NOT NULL,
	`obesity_score` integer NOT NULL,
	`fat_free_mass` real NOT NULL,
	`smi` real NOT NULL,
	`body_score` real NOT NULL,
	`target_weight` real NOT NULL,
	`weight_control` real NOT NULL,
	`fat_control` real NOT NULL,
	`muscle_control` real NOT NULL,
	`right_arm_fat_mass` real,
	`right_arm_fat_pct` real,
	`right_arm_fat_level` text,
	`right_arm_muscle_mass` real,
	`right_arm_muscle_pct` real,
	`right_arm_muscle_level` text,
	`right_arm_impedance_high` real,
	`right_arm_impedance_low` real,
	`left_arm_fat_mass` real,
	`left_arm_fat_pct` real,
	`left_arm_fat_level` text,
	`left_arm_muscle_mass` real,
	`left_arm_muscle_pct` real,
	`left_arm_muscle_level` text,
	`left_arm_impedance_high` real,
	`left_arm_impedance_low` real,
	`trunk_fat_mass` real,
	`trunk_fat_pct` real,
	`trunk_fat_level` text,
	`trunk_muscle_mass` real,
	`trunk_muscle_pct` real,
	`trunk_muscle_level` text,
	`trunk_impedance_high` real,
	`trunk_impedance_low` real,
	`right_leg_fat_mass` real,
	`right_leg_fat_pct` real,
	`right_leg_fat_level` text,
	`right_leg_muscle_mass` real,
	`right_leg_muscle_pct` real,
	`right_leg_muscle_level` text,
	`right_leg_impedance_high` real,
	`right_leg_impedance_low` real,
	`left_leg_fat_mass` real,
	`left_leg_fat_pct` real,
	`left_leg_fat_level` text,
	`left_leg_muscle_mass` real,
	`left_leg_muscle_pct` real,
	`left_leg_muscle_level` text,
	`left_leg_impedance_high` real,
	`left_leg_impedance_low` real,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `_user_date_uc` ON `recomp_records` (`user_id`,`date`);--> statement-breakpoint
CREATE TABLE `recomp_reports` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`record_id` integer NOT NULL,
	`file_path` text NOT NULL,
	`filename` text NOT NULL,
	`mime_type` text NOT NULL,
	`file_size` integer NOT NULL,
	`uploaded_at` integer NOT NULL,
	FOREIGN KEY (`record_id`) REFERENCES `recomp_records`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `recomp_reports_record_id_unique` ON `recomp_reports` (`record_id`);--> statement-breakpoint
CREATE TABLE `shared_link_audit_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`shared_link_id` text NOT NULL,
	`accessed_at` integer NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`status` text NOT NULL,
	FOREIGN KEY (`shared_link_id`) REFERENCES `shared_links`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `shared_links` (
	`id` text PRIMARY KEY NOT NULL,
	`owner_id` integer NOT NULL,
	`token` text NOT NULL,
	`description` text NOT NULL,
	`password_hash` text,
	`include_attachments` integer DEFAULT true NOT NULL,
	`expires_at` integer,
	`snapshot_data` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`owner_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `shared_links_token_unique` ON `shared_links` (`token`);--> statement-breakpoint
CREATE TABLE `users` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`email` text NOT NULL,
	`hashed_password` text NOT NULL,
	`display_name` text,
	`gender` text,
	`birthday` text,
	`height_cm` real,
	`target_weight_kg` real,
	`profile_image_path` text,
	`preferred_language` text,
	`email_confirmed` integer DEFAULT false NOT NULL,
	`pending_email` text,
	`verification_code` text,
	`verification_code_expires_at` integer,
	`verification_attempts` integer DEFAULT 0 NOT NULL,
	`reset_password_token` text,
	`reset_password_code` text,
	`reset_password_expires_at` integer,
	`reset_password_attempts` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);